version: '3.5'

services:

  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: sia_SOFT!2020
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  psql:
    name: psql
